version: "3.9"

services:
  postgresql:
    container_name: postgresql
    image: postgres:15.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgresql_data:
  mongodb_data:
